#!/bin/bash


function validateParameters() {
    if [ -z "$source_dir" ]; then
        echo "[ERROR]: Source directory is required"
        exit 1
    fi

    if [ -z "$destination_dir" ]; then
        echo "[ERROR]: Destination directory is required"
        exit 1
    fi

    if [ -z "$archive_name" ]; then
        echo "[ERROR]: Archive name is required"
        exit 1
    fi

    if [ -n "$period" ] && ! [[ "$period" =~ ^(daily|weekly|monthly)$ ]]; then
        echo "[ERROR]: Period must be 'daily', 'weekly' or 'monthly'"
        exit 1
    fi

    if [ -n "$time" ] && ! [[ "$time" =~ ^([0-1][0-9]|[2][0-3]):([0-5][0-9])$ ]]; then
        echo "[ERROR]: Time must be in format 'HH:MM'"
        exit 1
    fi
}