#!/bin/bash


function createFoldersAndFiles() {
    for (( i=0; i<$folders_count; i++ )); do
        folder_name="folder_${i}"
        folder_path="${path}/${folder_name}"
        mkdir -p "${folder_path}"

        for (( j=1; j<=$subfolders_count; j++ )); do
            subfolder_name="subfolder_${j}"
            subfolder_path="${folder_path}/${subfolder_name}"
            mkdir -p "${subfolder_path}"

            for (( k=1; k<=$files_count; k++ )); do
                file_name="file_${k}"
                file_path="${subfolder_path}/${file_name}"
                touch "${file_path}"
            done
        done
    done
}
