#!/bin/bash

source ./usage


# Arguments processing main function
function validateArguments() {
    # Parse given arguments
    while [ -n "$1" ]; do
        case "$1" in
            -h|--help)
                help
                exit 0
                ;;
            -t)
                shift
                handleTimeout "$1"
                ;;
            --time=*)
                handleTimeout $(extractValue "$1")
                ;;
            -e)
                shift
                handleProcessName "$1"
                ;;
            --process-name=*)
                handleProcessName $(extractValue "$1")
                ;;
            -d|--daemon)
                handleDaemon
                ;;
            *)
                handleUnknownArgument "$1"
                ;;
        esac
        shift
    done

    handleSkippedArguments
}


# Common functions

function isNumber() {
    local given_value=$1

    [[ $given_value =~ ^[0-9]+$ ]]
}

function extractValue() {
    local given_value=$1
    echo "${given_value#*=}"
}


# Processing functions

function handleTimeout() {
    if ! isNumber $1 || [ $1 -le 0 ]; then
        echo "Timeout must be a positive number"
        echo "Try main.sh --help for more information"
        exit 1
    fi

    if [ "$timeout" != "300" ]; then
        local argument_name="Timeout"
        handleAlreadyGivenArgument "$argument_name" "$timeout" "$1"
    fi

    timeout=$1
}

function handleProcessName() {
    if [ "$process_name" != "" ]; then
        local argument_name="Process name"
        handleAlreadyGivenArgument "$argument_name" "$process_name" "$1"
    fi

    process_name=$1
}

function handleDaemon() {
    run_as_daemon=0
}

function handleUnknownArgument() {
    local arg=$1

    if isNumber $arg; then
        handleTimeout $arg
    else
        handleProcessName "$arg"
    fi
}

function handleAlreadyGivenArgument() {
    local argument_name="$1"
    local already_set_value="$2"
    local argument_value="$3"

    echo "[WARNING] $argument_name already set. Updating."
    echo "Previous value='$already_set_value'. New one value='$argument_value'"
    echo "Try 'main.sh --help' for more information."
    echo
}

function handleSkippedArguments() {
    if [ "$process_name" = "" ]; then
        echo '[ERROR] You must pass process name to be watched.'
        echo "Try 'main.sh --help' for more information."
        exit 1
    fi
}
